-- MySQL Script generated by MySQL Workbench
-- mié 27 abr 2022 15:53:37
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema stc-wherehouse
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `stc-wherehouse` ;

-- -----------------------------------------------------
-- Schema stc-wherehouse
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `stc-wherehouse` ;
USE `stc-wherehouse` ;

-- -----------------------------------------------------
-- Table `stc-wherehouse`.`unidadmedida`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stc-wherehouse`.`unidadmedida` ;

CREATE TABLE IF NOT EXISTS `stc-wherehouse`.`unidadmedida` (
  `idunidadmedida` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `sistema` VARCHAR(45) NULL,
  `abreviatura` VARCHAR(45) NULL,
  PRIMARY KEY (`idunidadmedida`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stc-wherehouse`.`categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stc-wherehouse`.`categoria` ;

CREATE TABLE IF NOT EXISTS `stc-wherehouse`.`categoria` (
  `idcategoria` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `categoria_padre` INT NULL,
  PRIMARY KEY (`idcategoria`),
  INDEX `fk_categoria_categoria_idx` (`categoria_padre` ASC) VISIBLE,
  CONSTRAINT `fk_categoria_categoria`
    FOREIGN KEY (`categoria_padre`)
    REFERENCES `stc-wherehouse`.`categoria` (`idcategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stc-wherehouse`.`material`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stc-wherehouse`.`material` ;

CREATE TABLE IF NOT EXISTS `stc-wherehouse`.`material` (
  `idmaterial` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL,
  `descripcion` VARCHAR(200) NULL,
  `marca_comercial` VARCHAR(100) NULL,
  `status` VARCHAR(3) NULL,
  `unidadmedida_id` INT NOT NULL,
  `categoria_id` INT NOT NULL,
  PRIMARY KEY (`idmaterial`),
  INDEX `fk_material_unidadmedida1_idx` (`unidadmedida_id` ASC) VISIBLE,
  INDEX `fk_material_categoria1_idx` (`categoria_id` ASC) VISIBLE,
  CONSTRAINT `fk_material_unidadmedida1`
    FOREIGN KEY (`unidadmedida_id`)
    REFERENCES `stc-wherehouse`.`unidadmedida` (`idunidadmedida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_material_categoria1`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `stc-wherehouse`.`categoria` (`idcategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stc-wherehouse`.`proveedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stc-wherehouse`.`proveedor` ;

CREATE TABLE IF NOT EXISTS `stc-wherehouse`.`proveedor` (
  `idproveedor` INT NOT NULL AUTO_INCREMENT,
  `nit` VARCHAR(15) NULL,
  `nombre` VARCHAR(100) NULL,
  `direccion` VARCHAR(200) NULL,
  `telefono` VARCHAR(11) NULL,
  `contacto` VARCHAR(50) NULL,
  `email` VARCHAR(30) NULL,
  `status` VARCHAR(3) NULL,
  PRIMARY KEY (`idproveedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stc-wherehouse`.`tipo_documento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stc-wherehouse`.`tipo_documento` ;

CREATE TABLE IF NOT EXISTS `stc-wherehouse`.`tipo_documento` (
  `idtipo_documento` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(50) NULL,
  PRIMARY KEY (`idtipo_documento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stc-wherehouse`.`documento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stc-wherehouse`.`documento` ;

CREATE TABLE IF NOT EXISTS `stc-wherehouse`.`documento` (
  `iddocumento` INT NOT NULL AUTO_INCREMENT,
  `serie` VARCHAR(10) NULL,
  `numero` BIGINT NULL,
  `fecha` TIMESTAMP NULL,
  `status` VARCHAR(3) NULL,
  `tipo_documento_id` INT NOT NULL,
  `proveedor_id` INT NOT NULL,
  PRIMARY KEY (`iddocumento`),
  INDEX `fk_documento_tipo_documento1_idx` (`tipo_documento_id` ASC) VISIBLE,
  INDEX `fk_documento_proveedor1_idx` (`proveedor_id` ASC) VISIBLE,
  CONSTRAINT `fk_documento_tipo_documento1`
    FOREIGN KEY (`tipo_documento_id`)
    REFERENCES `stc-wherehouse`.`tipo_documento` (`idtipo_documento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_documento_proveedor1`
    FOREIGN KEY (`proveedor_id`)
    REFERENCES `stc-wherehouse`.`proveedor` (`idproveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stc-wherehouse`.`orden_compra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stc-wherehouse`.`orden_compra` ;

CREATE TABLE IF NOT EXISTS `stc-wherehouse`.`orden_compra` (
  `idorden_compra` INT NOT NULL AUTO_INCREMENT,
  `fecha_creacion` TIMESTAMP NULL,
  `fecha_entrega` TIMESTAMP NULL,
  `status` VARCHAR(3) NULL,
  `proveedor_id` INT NOT NULL,
  PRIMARY KEY (`idorden_compra`),
  INDEX `fk_orden_compra_proveedor1_idx` (`proveedor_id` ASC) VISIBLE,
  CONSTRAINT `fk_orden_compra_proveedor1`
    FOREIGN KEY (`proveedor_id`)
    REFERENCES `stc-wherehouse`.`proveedor` (`idproveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stc-wherehouse`.`posicion_compra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stc-wherehouse`.`posicion_compra` ;

CREATE TABLE IF NOT EXISTS `stc-wherehouse`.`posicion_compra` (
  `idposicion_compra` INT NOT NULL AUTO_INCREMENT,
  `orden_compra_id` INT NOT NULL,
  `material_id` INT NOT NULL,
  `cantidad` DECIMAL(10,2) NULL,
  PRIMARY KEY (`idposicion_compra`),
  INDEX `fk_posicion_compra_orden_compra1_idx` (`orden_compra_id` ASC) VISIBLE,
  INDEX `fk_posicion_compra_material1_idx` (`material_id` ASC) VISIBLE,
  CONSTRAINT `fk_posicion_compra_orden_compra1`
    FOREIGN KEY (`orden_compra_id`)
    REFERENCES `stc-wherehouse`.`orden_compra` (`idorden_compra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_posicion_compra_material1`
    FOREIGN KEY (`material_id`)
    REFERENCES `stc-wherehouse`.`material` (`idmaterial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stc-wherehouse`.`lote`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stc-wherehouse`.`lote` ;

CREATE TABLE IF NOT EXISTS `stc-wherehouse`.`lote` (
  `idlote` INT NOT NULL AUTO_INCREMENT,
  `fecha_creacion` TIMESTAMP NULL,
  `lote_proveedor` VARCHAR(50) NULL,
  `fecha_vencimiento` TIMESTAMP NULL,
  `fecha_produccion` TIMESTAMP NULL,
  `status` VARCHAR(3) NULL,
  PRIMARY KEY (`idlote`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stc-wherehouse`.`asigna_lote`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stc-wherehouse`.`asigna_lote` ;

CREATE TABLE IF NOT EXISTS `stc-wherehouse`.`asigna_lote` (
  `idasigna_lote` INT NOT NULL AUTO_INCREMENT,
  `lote_id` INT NOT NULL,
  `posicion_compra_id` INT NOT NULL,
  PRIMARY KEY (`idasigna_lote`),
  INDEX `fk_asigna_lote_lote1_idx` (`lote_id` ASC) VISIBLE,
  INDEX `fk_asigna_lote_posicion_compra1_idx` (`posicion_compra_id` ASC) VISIBLE,
  CONSTRAINT `fk_asigna_lote_lote1`
    FOREIGN KEY (`lote_id`)
    REFERENCES `stc-wherehouse`.`lote` (`idlote`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_asigna_lote_posicion_compra1`
    FOREIGN KEY (`posicion_compra_id`)
    REFERENCES `stc-wherehouse`.`posicion_compra` (`idposicion_compra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stc-wherehouse`.`recepcion_material`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stc-wherehouse`.`recepcion_material` ;

CREATE TABLE IF NOT EXISTS `stc-wherehouse`.`recepcion_material` (
  `idrecepcion_material` INT NOT NULL AUTO_INCREMENT,
  `fecha_recepcion` TIMESTAMP NULL,
  `orden_compra_id` INT NOT NULL,
  `documento_id` INT NOT NULL,
  PRIMARY KEY (`idrecepcion_material`),
  INDEX `fk_recepcion_material_orden_compra1_idx` (`orden_compra_id` ASC) VISIBLE,
  INDEX `fk_recepcion_material_documento1_idx` (`documento_id` ASC) VISIBLE,
  CONSTRAINT `fk_recepcion_material_orden_compra1`
    FOREIGN KEY (`orden_compra_id`)
    REFERENCES `stc-wherehouse`.`orden_compra` (`idorden_compra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_recepcion_material_documento1`
    FOREIGN KEY (`documento_id`)
    REFERENCES `stc-wherehouse`.`documento` (`iddocumento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stc-wherehouse`.`tipo_movimiento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stc-wherehouse`.`tipo_movimiento` ;

CREATE TABLE IF NOT EXISTS `stc-wherehouse`.`tipo_movimiento` (
  `idtipo_movimiento` INT NOT NULL AUTO_INCREMENT,
  `movimiento` VARCHAR(50) NULL,
  `descripcion` VARCHAR(100) NULL,
  `tipo_movimiento_padre` INT NULL,
  PRIMARY KEY (`idtipo_movimiento`),
  INDEX `fk_tipo_movimiento_tipo_movimiento1_idx` (`tipo_movimiento_padre` ASC) VISIBLE,
  CONSTRAINT `fk_tipo_movimiento_tipo_movimiento1`
    FOREIGN KEY (`tipo_movimiento_padre`)
    REFERENCES `stc-wherehouse`.`tipo_movimiento` (`idtipo_movimiento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stc-wherehouse`.`almacen`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stc-wherehouse`.`almacen` ;

CREATE TABLE IF NOT EXISTS `stc-wherehouse`.`almacen` (
  `idalmacen` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NULL,
  `telefono` VARCHAR(11) NULL,
  PRIMARY KEY (`idalmacen`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stc-wherehouse`.`ubicacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stc-wherehouse`.`ubicacion` ;

CREATE TABLE IF NOT EXISTS `stc-wherehouse`.`ubicacion` (
  `idubicacion` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NULL,
  `descripcion` VARCHAR(100) NULL,
  `status` VARCHAR(3) NULL,
  `almacen_idalmacen` INT NOT NULL,
  PRIMARY KEY (`idubicacion`),
  INDEX `fk_ubicacion_almacen1_idx` (`almacen_idalmacen` ASC) VISIBLE,
  CONSTRAINT `fk_ubicacion_almacen1`
    FOREIGN KEY (`almacen_idalmacen`)
    REFERENCES `stc-wherehouse`.`almacen` (`idalmacen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stc-wherehouse`.`movimiento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stc-wherehouse`.`movimiento` ;

CREATE TABLE IF NOT EXISTS `stc-wherehouse`.`movimiento` (
  `idmovimiento` INT NOT NULL AUTO_INCREMENT,
  `numero_documento` BIGINT NULL,
  `tipo_movimiento_id` INT NOT NULL,
  `material_id` INT NOT NULL,
  `lote_id` INT NOT NULL,
  `ubicacion_id` INT NOT NULL,
  `fecha_movimeinto` TIMESTAMP NULL,
  `observaciones` VARCHAR(200) NULL,
  PRIMARY KEY (`idmovimiento`),
  INDEX `fk_movimiento_tipo_movimiento1_idx` (`tipo_movimiento_id` ASC) VISIBLE,
  INDEX `fk_movimiento_material1_idx` (`material_id` ASC) VISIBLE,
  INDEX `fk_movimiento_lote1_idx` (`lote_id` ASC) VISIBLE,
  INDEX `fk_movimiento_ubicacion1_idx` (`ubicacion_id` ASC) VISIBLE,
  CONSTRAINT `fk_movimiento_tipo_movimiento1`
    FOREIGN KEY (`tipo_movimiento_id`)
    REFERENCES `stc-wherehouse`.`tipo_movimiento` (`idtipo_movimiento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_movimiento_material1`
    FOREIGN KEY (`material_id`)
    REFERENCES `stc-wherehouse`.`material` (`idmaterial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_movimiento_lote1`
    FOREIGN KEY (`lote_id`)
    REFERENCES `stc-wherehouse`.`lote` (`idlote`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_movimiento_ubicacion1`
    FOREIGN KEY (`ubicacion_id`)
    REFERENCES `stc-wherehouse`.`ubicacion` (`idubicacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stc-wherehouse`.`posicion_recepcion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stc-wherehouse`.`posicion_recepcion` ;

CREATE TABLE IF NOT EXISTS `stc-wherehouse`.`posicion_recepcion` (
  `idposicion_recepcion` INT NOT NULL AUTO_INCREMENT,
  `cantidad` DECIMAL(10,2) NULL,
  `precio_compra` DECIMAL(10,2) NULL,
  `movimiento_id` INT NOT NULL,
  `recepcion_material_id` INT NOT NULL,
  PRIMARY KEY (`idposicion_recepcion`, `recepcion_material_id`),
  INDEX `fk_posicion_recepcion_movimiento1_idx` (`movimiento_id` ASC) VISIBLE,
  INDEX `fk_posicion_recepcion_recepcion_material1_idx` (`recepcion_material_id` ASC) VISIBLE,
  CONSTRAINT `fk_posicion_recepcion_movimiento1`
    FOREIGN KEY (`movimiento_id`)
    REFERENCES `stc-wherehouse`.`movimiento` (`idmovimiento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_posicion_recepcion_recepcion_material1`
    FOREIGN KEY (`recepcion_material_id`)
    REFERENCES `stc-wherehouse`.`recepcion_material` (`idrecepcion_material`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stc-wherehouse`.`existencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stc-wherehouse`.`existencia` ;

CREATE TABLE IF NOT EXISTS `stc-wherehouse`.`existencia` (
  `idexistencia` INT NOT NULL AUTO_INCREMENT,
  `saldo` DECIMAL(10,2) NULL,
  `precio_venta` DECIMAL(10,2) NULL,
  `ubicacion_id` INT NOT NULL,
  `material_id` INT NOT NULL,
  `lote_id` INT NOT NULL,
  PRIMARY KEY (`idexistencia`),
  INDEX `fk_existencia_ubicacion1_idx` (`ubicacion_id` ASC) VISIBLE,
  INDEX `fk_existencia_material1_idx` (`material_id` ASC) VISIBLE,
  INDEX `fk_existencia_lote1_idx` (`lote_id` ASC) VISIBLE,
  CONSTRAINT `fk_existencia_ubicacion1`
    FOREIGN KEY (`ubicacion_id`)
    REFERENCES `stc-wherehouse`.`ubicacion` (`idubicacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_existencia_material1`
    FOREIGN KEY (`material_id`)
    REFERENCES `stc-wherehouse`.`material` (`idmaterial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_existencia_lote1`
    FOREIGN KEY (`lote_id`)
    REFERENCES `stc-wherehouse`.`lote` (`idlote`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stc-wherehouse`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stc-wherehouse`.`cliente` ;

CREATE TABLE IF NOT EXISTS `stc-wherehouse`.`cliente` (
  `idcliente` INT NOT NULL AUTO_INCREMENT,
  `nit` VARCHAR(10) NULL,
  `nombre` VARCHAR(50) NULL,
  `apellido` VARCHAR(50) NULL,
  `direccion` VARCHAR(50) NULL,
  `telefono` VARCHAR(11) NULL,
  `status` VARCHAR(3) NULL,
  PRIMARY KEY (`idcliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stc-wherehouse`.`venta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stc-wherehouse`.`venta` ;

CREATE TABLE IF NOT EXISTS `stc-wherehouse`.`venta` (
  `idventa` INT NOT NULL AUTO_INCREMENT,
  `fecha` TIMESTAMP NULL,
  `forma_pago` VARCHAR(5) NULL,
  `cliente_id` INT NOT NULL,
  PRIMARY KEY (`idventa`),
  INDEX `fk_venta_cliente1_idx` (`cliente_id` ASC) VISIBLE,
  CONSTRAINT `fk_venta_cliente1`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `stc-wherehouse`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stc-wherehouse`.`posicion_venta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stc-wherehouse`.`posicion_venta` ;

CREATE TABLE IF NOT EXISTS `stc-wherehouse`.`posicion_venta` (
  `idposicion_venta` INT NOT NULL AUTO_INCREMENT,
  `cantidad` DECIMAL(10,2) NULL,
  `descuento` DECIMAL(10,2) NULL,
  `material_id` INT NOT NULL,
  `venta_id` INT NOT NULL,
  PRIMARY KEY (`idposicion_venta`, `venta_id`),
  INDEX `fk_posicion_venta_material1_idx` (`material_id` ASC) VISIBLE,
  INDEX `fk_posicion_venta_venta1_idx` (`venta_id` ASC) VISIBLE,
  CONSTRAINT `fk_posicion_venta_material1`
    FOREIGN KEY (`material_id`)
    REFERENCES `stc-wherehouse`.`material` (`idmaterial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_posicion_venta_venta1`
    FOREIGN KEY (`venta_id`)
    REFERENCES `stc-wherehouse`.`venta` (`idventa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stc-wherehouse`.`entrega`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stc-wherehouse`.`entrega` ;

CREATE TABLE IF NOT EXISTS `stc-wherehouse`.`entrega` (
  `identrega` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(3) NULL,
  `venta_id` INT NOT NULL,
  PRIMARY KEY (`identrega`),
  INDEX `fk_entrega_venta1_idx` (`venta_id` ASC) VISIBLE,
  CONSTRAINT `fk_entrega_venta1`
    FOREIGN KEY (`venta_id`)
    REFERENCES `stc-wherehouse`.`venta` (`idventa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stc-wherehouse`.`posicion_entrega`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stc-wherehouse`.`posicion_entrega` ;

CREATE TABLE IF NOT EXISTS `stc-wherehouse`.`posicion_entrega` (
  `idposicion_entrega` INT NOT NULL AUTO_INCREMENT,
  `cantidad` DECIMAL(10,2) NULL,
  `material_id` INT NOT NULL,
  `entrega_id` INT NOT NULL,
  PRIMARY KEY (`idposicion_entrega`),
  INDEX `fk_posicion_entrega_material1_idx` (`material_id` ASC) VISIBLE,
  INDEX `fk_posicion_entrega_entrega1_idx` (`entrega_id` ASC) VISIBLE,
  CONSTRAINT `fk_posicion_entrega_material1`
    FOREIGN KEY (`material_id`)
    REFERENCES `stc-wherehouse`.`material` (`idmaterial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_posicion_entrega_entrega1`
    FOREIGN KEY (`entrega_id`)
    REFERENCES `stc-wherehouse`.`entrega` (`identrega`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stc-wherehouse`.`picking`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stc-wherehouse`.`picking` ;

CREATE TABLE IF NOT EXISTS `stc-wherehouse`.`picking` (
  `idpicking` INT NOT NULL AUTO_INCREMENT,
  `cantidad` DECIMAL(10,2) NULL,
  `fecha` TIMESTAMP NULL,
  `movimiento_id` INT NOT NULL,
  `posicion_entrega_id` INT NOT NULL,
  PRIMARY KEY (`idpicking`),
  INDEX `fk_picking_movimiento1_idx` (`movimiento_id` ASC) VISIBLE,
  INDEX `fk_picking_posicion_entrega1_idx` (`posicion_entrega_id` ASC) VISIBLE,
  CONSTRAINT `fk_picking_movimiento1`
    FOREIGN KEY (`movimiento_id`)
    REFERENCES `stc-wherehouse`.`movimiento` (`idmovimiento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_picking_posicion_entrega1`
    FOREIGN KEY (`posicion_entrega_id`)
    REFERENCES `stc-wherehouse`.`posicion_entrega` (`idposicion_entrega`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stc-wherehouse`.`factura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stc-wherehouse`.`factura` ;

CREATE TABLE IF NOT EXISTS `stc-wherehouse`.`factura` (
  `idfactura` INT NOT NULL AUTO_INCREMENT,
  `fecha` TIMESTAMP NULL,
  `status` VARCHAR(3) NULL,
  `serie` VARCHAR(15) NULL,
  `numero` BIGINT NULL,
  `cliente_id` INT NOT NULL,
  `cliente_id` INT NOT NULL,
  PRIMARY KEY (`idfactura`, `cliente_id`),
  INDEX `fk_factura_cliente1_idx` (`cliente_id` ASC) VISIBLE,
  CONSTRAINT `fk_factura_cliente1`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `stc-wherehouse`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stc-wherehouse`.`posicion_factura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stc-wherehouse`.`posicion_factura` ;

CREATE TABLE IF NOT EXISTS `stc-wherehouse`.`posicion_factura` (
  `idposicion_factura` INT NOT NULL AUTO_INCREMENT,
  `factura_id` INT NOT NULL,
  `entrega_id` INT NOT NULL,
  PRIMARY KEY (`idposicion_factura`, `factura_id`),
  INDEX `fk_posicion_factura_factura1_idx` (`factura_id` ASC) VISIBLE,
  INDEX `fk_posicion_factura_entrega1_idx` (`entrega_id` ASC) VISIBLE,
  CONSTRAINT `fk_posicion_factura_factura1`
    FOREIGN KEY (`factura_id`)
    REFERENCES `stc-wherehouse`.`factura` (`idfactura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_posicion_factura_entrega1`
    FOREIGN KEY (`entrega_id`)
    REFERENCES `stc-wherehouse`.`entrega` (`identrega`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stc-wherehouse`.`embalaje`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stc-wherehouse`.`embalaje` ;

CREATE TABLE IF NOT EXISTS `stc-wherehouse`.`embalaje` (
  `idembalaje` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(50) NULL,
  PRIMARY KEY (`idembalaje`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stc-wherehouse`.`asigna_embalaje`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stc-wherehouse`.`asigna_embalaje` ;

CREATE TABLE IF NOT EXISTS `stc-wherehouse`.`asigna_embalaje` (
  `idasigna_embalaje` INT NOT NULL AUTO_INCREMENT,
  `cantidad` BIGINT NULL,
  `embalaje_id` INT NOT NULL,
  `entrega_id` INT NOT NULL,
  PRIMARY KEY (`idasigna_embalaje`),
  INDEX `fk_asigna_embalaje_embalaje1_idx` (`embalaje_id` ASC) VISIBLE,
  INDEX `fk_asigna_embalaje_entrega1_idx` (`entrega_id` ASC) VISIBLE,
  CONSTRAINT `fk_asigna_embalaje_embalaje1`
    FOREIGN KEY (`embalaje_id`)
    REFERENCES `stc-wherehouse`.`embalaje` (`idembalaje`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_asigna_embalaje_entrega1`
    FOREIGN KEY (`entrega_id`)
    REFERENCES `stc-wherehouse`.`entrega` (`identrega`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
