-- MySQL Script generated by MySQL Workbench
-- lun 09 may 2022 21:00:38
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema security
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `security` ;

-- -----------------------------------------------------
-- Schema security
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `security` ;
USE `security` ;

-- -----------------------------------------------------
-- Table `security`.`rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `security`.`rol` ;

CREATE TABLE IF NOT EXISTS `security`.`rol` (
  `idrol` INT NOT NULL AUTO_INCREMENT,
  `nomre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(100) NULL,
  PRIMARY KEY (`idrol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `security`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `security`.`usuario` ;

CREATE TABLE IF NOT EXISTS `security`.`usuario` (
  `usuarioid` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NULL,
  `apellido` VARCHAR(50) NULL,
  `alias` VARCHAR(25) NULL,
  `password` VARCHAR(45) NULL,
  `rol_idrol` INT NOT NULL,
  PRIMARY KEY (`usuarioid`),
  CONSTRAINT `fk_usuario_rol1`
    FOREIGN KEY (`rol_idrol`)
    REFERENCES `security`.`rol` (`idrol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_usuario_rol1_idx` ON `security`.`usuario` (`rol_idrol` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `security`.`perfil`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `security`.`perfil` ;

CREATE TABLE IF NOT EXISTS `security`.`perfil` (
  `perfilid` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(25) NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`perfilid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `security`.`servicio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `security`.`servicio` ;

CREATE TABLE IF NOT EXISTS `security`.`servicio` (
  `idservicio` INT NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(45) NULL,
  `descripcion` VARCHAR(50) NULL,
  PRIMARY KEY (`idservicio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `security`.`asigna_perfil`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `security`.`asigna_perfil` ;

CREATE TABLE IF NOT EXISTS `security`.`asigna_perfil` (
  `idasigna_perfil` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` INT NOT NULL,
  `perfil_id` INT NOT NULL,
  PRIMARY KEY (`idasigna_perfil`),
  CONSTRAINT `fk_asigna_perfil_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `security`.`usuario` (`usuarioid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_asigna_perfil_perfil1`
    FOREIGN KEY (`perfil_id`)
    REFERENCES `security`.`perfil` (`perfilid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_asigna_perfil_usuario1_idx` ON `security`.`asigna_perfil` (`usuario_id` ASC) VISIBLE;

CREATE INDEX `fk_asigna_perfil_perfil1_idx` ON `security`.`asigna_perfil` (`perfil_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `security`.`Autorizacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `security`.`Autorizacion` ;

CREATE TABLE IF NOT EXISTS `security`.`Autorizacion` (
  `idAutorizacion` INT NOT NULL AUTO_INCREMENT,
  `servicio_id` INT NOT NULL,
  `perfil_id` INT NOT NULL,
  PRIMARY KEY (`idAutorizacion`),
  CONSTRAINT `fk_Autorizacion_servicio1`
    FOREIGN KEY (`servicio_id`)
    REFERENCES `security`.`servicio` (`idservicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Autorizacion_perfil1`
    FOREIGN KEY (`perfil_id`)
    REFERENCES `security`.`perfil` (`perfilid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Autorizacion_servicio1_idx` ON `security`.`Autorizacion` (`servicio_id` ASC) VISIBLE;

CREATE INDEX `fk_Autorizacion_perfil1_idx` ON `security`.`Autorizacion` (`perfil_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `security`.`login_sesion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `security`.`login_sesion` ;

CREATE TABLE IF NOT EXISTS `security`.`login_sesion` (
  `idlogin_sesion` INT NOT NULL AUTO_INCREMENT,
  `fecha_ingreso` TIMESTAMP NULL,
  `fecha_final` TIMESTAMP NULL,
  `estado` VARCHAR(10) NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`idlogin_sesion`),
  CONSTRAINT `fk_login_sesion_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `security`.`usuario` (`usuarioid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_login_sesion_usuario1_idx` ON `security`.`login_sesion` (`usuario_id` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
